version: '3'

services:
  backend:
    build:
      context: ./backend
    # deploy:
    #   replicas: 3  # Habilité las réplicas para tener múltiples instancias para el load balancing
    # No exponemos los puertos directamente ya que Caddy se encargará del acceso
    # ports:
    #   - '8002:8000'
    environment:
      - MONGODB_CONNECTION_STRING=mongodb+srv://maverickUser:c9f5TdlLZCxDisgO@cluster0.xi11h.mongodb.net/reservation-testing-bd?retryWrites=true&w=majority&appName=Cluster0
      - SERVER_PORT=8000
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    restart: always
    networks:
      - app-network
    # Para que Caddy identifique cada instancia
    hostname: "backend-{{.Task.Slot}}"

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    restart: always
    networks:
      - app-network

  caddy:
    image: caddy:2
    container_name: caddy-container
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: