services:
  backend:
    build:
      context: ./backend
    # deploy:
    #   replicas: 4
    ports:
      - '8002:8000'
    environment:
      - MONGODB_CONNECTION_STRING=mongodb+srv://maverickUser:c9f5TdlLZCxDisgO@cluster0.xi11h.mongodb.net/reservation-testing-bd?retryWrites=true&w=majority&appName=Cluster0

    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    restart: always

  caddy:
    image: caddy:2
    container_name: caddy-container
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
