# .github/workflows/branch-validation.yml
name: Branch Validation

on:
  push:
    branches:
      - main
      - testing
      - staging
  pull_request:
    branches:
      - main
      - testing
      - staging

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Start development server
        run: |
          npm run dev &
          # Esperar a que el servidor esté listo
          sleep 10
        
      - name: Run E2E tests
        run: npm run e2e
      
      - name: Stop development server
        run: pkill -f "npm run dev" || true

  # Trabajo de despliegue (CD) - Solo se ejecuta en pushes a main
  deploy:
    runs-on: self-hosted
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy with Docker Compose
        run: |
          # Detiene los contenedores existentes si es necesario
          docker-compose down
          
          # Construye y levanta los contenedores
          docker-compose up -d --build
          
      - name: Verify deployment
        run: |
          # Espera unos segundos para que los servicios se inicien completamente
          sleep 10
          
          # Verifica que los contenedores estén en ejecución
          docker-compose ps